### ISSUE TITLE
Direct to the proper page

### ISSUE THREAD

**Issue by mlhwang** [gyoshil/monsterappetite#11]
There seems to be a linking issue where the second time the PDQ is done it does not go to the "Thank you" message.

**Comment by santolucito** [comment]
maybe this has to do with not having a cached user?

**Comment by mlhwang** [comment]
PDQ 1st and 2nd time need to be directed to the right place.

After 1st PDQ: BIQ (which is currently correct)
After 2nd PDQ: Thanks page

**Comment by santolucito** [comment]
can you double check that this is stilla  bug?

**Comment by mlhwang** [comment]
Once #26 is fixed this should also be fixed (theoretically speaking)

**Comment by mlhwang** [comment]
#26 has been addressed and fixed but the proper page (thank you page) still does not load after the second BIQ page.

**Comment by mlhwang** [comment]
Solved.
