### ISSUE TITLE
No user cookie

### ISSUE THREAD

**Issue by mlhwang** [gyoshil/monsterappetite#14]
On any page that reads the Player cookie, throw and error and redirect to a user reg page.

When a potential subject somehow wonders off to a page before his or her ID is created in the user data base, we need a system that will send en error message that a user has NOT been created and therefore a user needs to be created to participate in any online activities.

**Comment by santolucito** [comment]
fixed with b20f07d40e38845fa784206861f05ef1f0bc2a06 and c557005a12c8e9e9b2b091b7fc9c22ef571df278
