### ISSUE TITLE
Add item information

### ISSUE THREAD

**Issue by santolucito** [gyoshil/monsterappetite#15]
Add information besides calories and names to item in the deck.

Should include
name, imageLocation, calories, fat, protien, etc

**Comment by santolucito** [comment]
There is a csv file in 'private/foodcard_database.csv' that, once filled out, can be the source of card data for the game. This makes is much easier to edit the card database.

**Comment by santolucito** [comment]
Actually, this can be completed by writing a small script to export the DECK object in model.js to a csv file. Then, we will need to manually edit the csv, but at least most of the work will be automated.

**Comment by mlhwang** [comment]
All of the CSV items have been entered and updated. issues fixed with a304f08244a304705b43fba34fbca457037bd0ce
