### ISSUE TITLE
Add a sequential step-by-step unfolding of events in MA

### ISSUE THREAD

**Issue by mlhwang** [gyoshil/monsterappetite#25]
1. snack is selected
2. on top of item a plus sign and calories displayed
3. snack pic is added to the calorie board on the right (pic1 + pic2 + pic3)
4. then all snacks' calories are counted up
5. then monster gets fat accordingly

This kind of sequence of events will be easier on the eye (less busy and less all over the page) and less cognitive load.

**Comment by santolucito** [comment]
adding the calories on the image is good enough
